apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: Always
        ports:
        - name: kafka-port
          containerPort: 9092
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_CREATE_TOPICS
            value: "prices:3:1"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafka-service"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "localhost:2181"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://:9092
      - name: zookeeper
        image: wurstmeister/zookeeper
        imagePullPolicy: Always
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"        
        ports:
        - containerPort: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-zookeeper
  ports:
  - protocol: TCP
    port: 9092
    targetPort: kafka-port