apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-service
  labels:
    app: position-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-service
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: position-service
    spec:
      containers:
      - name: position-service
        image: position-service:latest
        imagePullPolicy: Never
        env: 
          - name: PRICE_PROVIDER_URI
            value: "price-service:7073"
          - name: POSTGRES_DB_URI
            value: "postgres://user:password@postgres:5432/chart?sslmode=disable"
        ports:
        - name: host-port
          containerPort: 7074
        livenessProbe:
          grpc:
            port: 7074
          initialDelaySeconds: 10
          periodSeconds: 5

--- 

apiVersion: v1
kind: Service
metadata:
  name: position-service
spec:
  selector:
    app: position-service
  ports:
  - protocol: TCP
    port: 7074
    targetPort: host-port