apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-chart
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_DB
          value: chart
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        image: postgres:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: chart-data
      restartPolicy: Always
      volumes:
      - name: chart-data
        persistentVolumeClaim:
          claimName: chart-data
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chart-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}