apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service
  labels:
    app: price-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-service
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: price-service
    spec:
      containers:
      - name: price-service
        image: price-service:latest
        imagePullPolicy: Never # change if nessasary
        ports:
        - name: rpc-chart-port
          containerPort: 7071
        - name: rpc-pos-port
          containerPort: 7073
        env:
        - name: KAFKA_URL
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "prices"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0?protocol=3"
        - name: RPC_CHART_PORT
          value: "7071"
        - name: RPC_POS_PORT
          value: "7073"
        # livenessProbe: #for two ports?
        #   grpc:
        #     port: 7071
        #   initialDelaySeconds: 10
        #   periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: price-service
spec:
  selector:
    app: price-service
  ports:
  - name: "7071"
    protocol: TCP
    port: 7071
    targetPort: rpc-chart-port
  - name: "7073"
    protocol: TCP
    port: 7073
    targetPort: rpc-pos-port